apiVersion: apps/v1
kind: Deployment
metadata:
  name: ban-service-working
  namespace: z-grid
  labels:
    app: ban-service-working
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ban-service-working
  template:
    metadata:
      labels:
        app: ban-service-working
    spec:
      containers:
      - name: ban-service-working
        image: python:3.11-slim
        command:
        - /bin/bash
        - -c
        - |
          pip install flask requests
          python3 -c "
          from flask import Flask, request, jsonify
          from datetime import datetime
          import json
          import sqlite3
          import os

          app = Flask(__name__)

          BAN_API_KEYS = ['ban123', 'supersecret123', 'biasyavar', 'enhancedban123']

          # Initialize in-memory database - thread safe
          banned_users = {}

          def init_db():
              # Create some initial data
              global banned_users
              banned_users = {
                  'test_banned_user': {
                      'user_id': 'test_banned_user',
                      'reason': 'Test ban',
                      'banned_at': datetime.now().isoformat(),
                      'banned_by': 'system'
                  }
              }

          init_db()

          def validate_api_key():
              api_key = request.headers.get('X-API-Key')
              return api_key in BAN_API_KEYS

          @app.route('/health', methods=['GET'])
          def health():
              return jsonify({
                  'ok': True,
                  'service': 'Ban Service',
                  'status': 'running',
                  'timestamp': datetime.now().isoformat()
              })

          @app.route('/ban/check', methods=['GET'])
          def check_ban():
              user_id = request.args.get('user_id')
              if not user_id:
                  return jsonify({'error': 'user_id parameter required'}), 400

              if user_id in banned_users:
                  ban_info = banned_users[user_id]
                  return jsonify({
                      'user_id': user_id,
                      'banned': True,
                      'reason': ban_info['reason'],
                      'banned_at': ban_info['banned_at'],
                      'banned_by': ban_info['banned_by']
                  })
              else:
                  return jsonify({
                      'user_id': user_id,
                      'banned': False
                  })

          @app.route('/ban/add', methods=['POST'])
          def add_ban():
              if not validate_api_key():
                  return jsonify({'error': 'Invalid API key'}), 401

              data = request.get_json()
              if not data or 'user_id' not in data or 'reason' not in data:
                  return jsonify({'error': 'user_id and reason are required'}), 400

              banned_users[data['user_id']] = {
                  'user_id': data['user_id'],
                  'reason': data['reason'],
                  'banned_at': datetime.now().isoformat(),
                  'banned_by': 'system'
              }

              return jsonify({
                  'user_id': data['user_id'],
                  'banned': True,
                  'reason': data['reason'],
                  'banned_at': datetime.now().isoformat(),
                  'banned_by': 'system'
              })

          @app.route('/ban/remove', methods=['POST'])
          def remove_ban():
              if not validate_api_key():
                  return jsonify({'error': 'Invalid API key'}), 401

              data = request.get_json()
              if not data or 'user_id' not in data:
                  return jsonify({'error': 'user_id is required'}), 400

              if data['user_id'] in banned_users:
                  del banned_users[data['user_id']]

              return jsonify({
                  'user_id': data['user_id'],
                  'banned': False,
                  'unbanned_at': datetime.now().isoformat()
              })

          if __name__ == '__main__':
              print(\"🚀 Ban Service Starting...\")
              app.run(host='0.0.0.0', port=8010, debug=False)
          "
        ports:
        - containerPort: 8010
        env:
        - name: BAN_API_KEYS
          value: "ban123,supersecret123,biasyavar,enhancedban123"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ban-service-working
  namespace: z-grid
spec:
  selector:
    app: ban-service-working
  ports:
  - port: 8010
    targetPort: 8010
  type: LoadBalancer