apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gibberish-model-pvc
  namespace: z-grid
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: default