apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test-monitor
  namespace: z-grid
  labels:
    app: load-test-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-test-monitor
  template:
    metadata:
      labels:
        app: load-test-monitor
    spec:
      containers:
      - name: monitor
        image: nginx:alpine
        ports:
        - containerPort: 80
        command: ["/bin/sh"]
        args:
          - -c
          - |
            # Create monitoring dashboard
            cat > /usr/share/nginx/html/index.html << 'EOF'
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Gateway V2 Load Test Monitor</title>
                <style>
                    body {
                        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                        margin: 0;
                        padding: 20px;
                        background-color: #f5f5f5;
                    }
                    .container {
                        max-width: 1200px;
                        margin: 0 auto;
                        background: white;
                        border-radius: 8px;
                        box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                        padding: 30px;
                    }
                    h1 {
                        color: #2c3e50;
                        text-align: center;
                        margin-bottom: 30px;
                    }
                    .test-config {
                        background: #ecf0f1;
                        padding: 20px;
                        border-radius: 6px;
                        margin-bottom: 30px;
                    }
                    .config-item {
                        display: flex;
                        justify-content: space-between;
                        margin: 10px 0;
                        padding: 8px;
                        background: white;
                        border-radius: 4px;
                    }
                    .config-label {
                        font-weight: bold;
                        color: #34495e;
                    }
                    .config-value {
                        color: #3498db;
                    }
                    .services-grid {
                        display: grid;
                        grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
                        gap: 20px;
                        margin-bottom: 30px;
                    }
                    .service-card {
                        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                        color: white;
                        padding: 20px;
                        border-radius: 8px;
                        text-align: center;
                    }
                    .service-name {
                        font-size: 18px;
                        font-weight: bold;
                        margin-bottom: 10px;
                    }
                    .service-endpoint {
                        font-size: 12px;
                        opacity: 0.9;
                    }
                    .status-section {
                        text-align: center;
                        padding: 40px;
                        background: #2ecc71;
                        color: white;
                        border-radius: 8px;
                        margin-bottom: 30px;
                    }
                    .status-title {
                        font-size: 24px;
                        margin-bottom: 15px;
                    }
                    .status-details {
                        font-size: 16px;
                        line-height: 1.6;
                    }
                    .refresh-info {
                        text-align: center;
                        margin-top: 30px;
                        color: #7f8c8d;
                    }
                    .timestamp {
                        font-weight: bold;
                        color: #3498db;
                    }
                </style>
            </head>
            <body>
                <div class="container">
                    <h1>🚀 Gateway V2 Load Test Monitor</h1>

                    <div class="test-config">
                        <h2>📊 Test Configuration</h2>
                        <div class="config-item">
                            <span class="config-label">Target Service:</span>
                            <span class="config-value">gateway-v2-service.z-grid:8008</span>
                        </div>
                        <div class="config-item">
                            <span class="config-label">Test Duration:</span>
                            <span class="config-value">48 hours</span>
                        </div>
                        <div class="config-item">
                            <span class="config-label">Requests per Hour:</span>
                            <span class="config-value">1,000</span>
                        </div>
                        <div class="config-item">
                            <span class="config-label">Total Requests:</span>
                            <span class="config-value">48,000</span>
                        </div>
                        <div class="config-item">
                            <span class="config-label">Request Interval:</span>
                            <span class="config-value">3.6 seconds</span>
                        </div>
                        <div class="config-item">
                            <span class="config-label">Concurrent Workers:</span>
                            <span class="config-value">10</span>
                        </div>
                    </div>

                    <div class="services-grid">
                        <div class="service-card">
                            <div class="service-name">🧠 DeBERTa Bias Detection</div>
                            <div class="service-endpoint">bias-deberta-v3.z-grid:8012</div>
                        </div>
                        <div class="service-card">
                            <div class="service-name">☠️ Toxicity Detection</div>
                            <div class="service-endpoint">tox-service-ml-enabled.z-grid:8001</div>
                        </div>
                        <div class="service-card">
                            <div class="service-name">🔍 PII Detection</div>
                            <div class="service-endpoint">pii-enhanced-v3-service.z-grid:8000</div>
                        </div>
                        <div class="service-card">
                            <div class="service-name">🔑 Secrets Detection</div>
                            <div class="service-endpoint">secrets-service-yavar-fixed.z-grid:8005</div>
                        </div>
                        <div class="service-card">
                            <div class="service-name">🛡️ Jailbreak Detection</div>
                            <div class="service-endpoint">jailbreak-service-yavar-fixed.z-grid:8002</div>
                        </div>
                        <div class="service-card">
                            <div class="service-name">📋 Format Validation</div>
                            <div class="service-endpoint">format-service-yavar-fixed.z-grid:8006</div>
                        </div>
                        <div class="service-card">
                            <div class="service-name">🔤 Gibberish Detection</div>
                            <div class="service-endpoint">gibberish-service-yavar-fixed.z-grid:8007</div>
                        </div>
                    </div>

                    <div class="status-section">
                        <div class="status-title">🏃 Load Test Status</div>
                        <div class="status-details">
                            <strong>Currently Running</strong><br>
                            Load test is actively sending requests to all 7 internal services<br>
                            Each request tests: PII, Toxicity, Bias, Secrets, Jailbreak, Format, and Gibberish detection
                        </div>
                    </div>

                    <div style="background: #e8f4fd; padding: 20px; border-radius: 8px; margin-bottom: 30px;">
                        <h3 style="color: #2c3e50; margin-top: 0;">📋 Test Scenarios</h3>
                        <ul style="color: #34495e; line-height: 1.6;">
                            <li><strong>Clean Content:</strong> Normal conversation text</li>
                            <li><strong>PII Detection:</strong> Email addresses, phone numbers, SSN, addresses</li>
                            <li><strong>Toxicity Detection:</strong> Profanity and abusive language</li>
                            <li><strong>Bias Detection:</strong> Stereotypes and discriminatory content</li>
                            <li><strong>Secrets Detection:</strong> API keys, credentials, tokens</li>
                            <li><strong>Jailbreak Detection:</strong> Prompt injection attempts</li>
                            <li><strong>Format Violations:</strong> Invalid order numbers, tracking IDs</li>
                            <li><strong>Gibberish Detection:</strong> Nonsense and random text</li>
                            <li><strong>Mixed Violations:</strong> Content triggering multiple services</li>
                            <li><strong>Long Complex Content:</strong> Extended text with various violations</li>
                        </ul>
                    </div>

                    <div style="background: #fff3cd; padding: 20px; border-radius: 8px; margin-bottom: 30px;">
                        <h3 style="color: #856404; margin-top: 0;">📊 Monitoring Information</h3>
                        <p style="color: #856404; margin: 0;">
                            <strong>Logs:</strong> Available in load-test-logs-pvc<br>
                            <strong>Reports:</strong> Generated in load-test-reports-pvc<br>
                            <strong>Progress Updates:</strong> Every 100 requests in logs<br>
                            <strong>Final Report:</strong> JSON format with detailed metrics
                        </p>
                    </div>

                    <div class="refresh-info">
                        <p>
                            📊 Load test started: <span class="timestamp" id="start-time"></span><br>
                            🔄 Page auto-refreshes every 30 seconds<br>
                            ⏱️ Expected completion: <span class="timestamp" id="end-time"></span>
                        </p>
                    </div>
                </div>

                <script>
                    // Set timestamps
                    const startTime = new Date();
                    const endTime = new Date(startTime.getTime() + 48 * 60 * 60 * 1000);

                    document.getElementById('start-time').textContent = startTime.toLocaleString();
                    document.getElementById('end-time').textContent = endTime.toLocaleString();

                    // Auto-refresh every 30 seconds
                    setTimeout(() => {
                        location.reload();
                    }, 30000);
                </script>
            </body>
            </html>
            EOF

            echo "🖥️ Load test monitor dashboard ready"
            echo "🌐 Access via: kubectl port-forward service/load-test-monitor-service 8080:80"
            echo "📊 Then open: http://localhost:8080"

            nginx -g 'daemon off;'
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 50m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: load-test-monitor-service
  namespace: z-grid
  labels:
    app: load-test-monitor
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: load-test-monitor