apiVersion: v1
kind: Pod
metadata:
  name: model-copy
  namespace: z-grid
spec:
  containers:
  - name: model-copy
    image: busybox
    command: ['sh', '-c', 'echo "Model copy completed. Sleeping..." && sleep 3600']
    volumeMounts:
    - name: model-storage
      mountPath: /app/models
  volumes:
  - name: model-storage
    persistentVolumeClaim:
      claimName: llamaguard-model-pvc
  restartPolicy: Never