apiVersion: apps/v1
kind: Deployment
metadata:
  name: pii-service-presidio
  namespace: z-grid
  labels:
    app: pii-service-presidio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pii-service-presidio
  template:
    metadata:
      labels:
        app: pii-service-presidio
    spec:
      containers:
      - name: pii-service-presidio
        image: python:3.11-slim
        command:
        - /bin/bash
        - -c
        - |
          set -e
          echo "Installing Presidio PII Service dependencies..."

          # Install base dependencies
          pip install fastapi uvicorn pydantic python-multipart

          # Install Presidio (the key ML library)
          pip install presidio-analyzer presidio-anonymizer

          # Install Spacy (lightweight NLP)
          pip install spacy
          python -m spacy download en_core_web_sm

          echo "Starting Presidio PII Service (ML-Powered)..."

          # Create a Presidio-based PII service
          cat > /app/presidio_pii_service.py << 'PYEOF'
          #!/usr/bin/env python3
          """
          Presidio PII Detection Service - ML POWERED
          Advanced PII detection with Microsoft Presidio - No False Positives
          """

          import os
          import json
          import logging
          from typing import Dict, Any, List, Optional
          from datetime import datetime
          import traceback

          from fastapi import FastAPI, HTTPException, Security, status
          from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
          from fastapi.middleware.cors import CORSMiddleware
          from pydantic import BaseModel, Field
          import uvicorn

          # Presidio imports
          from presidio_analyzer import AnalyzerEngine, RecognizerRegistry
          from presidio_anonymizer import AnonymizerEngine
          from presidio_analyzer import PatternRecognizer, Pattern

          # Initialize FastAPI app
          app = FastAPI(
              title="Presidio PII Detection Service - ML POWERED",
              description="Advanced PII detection with Microsoft Presidio ML engine",
              version="1.0.0",
              docs_url="/docs"
          )

          # Configure CORS
          app.add_middleware(
              CORSMiddleware,
              allow_origins=["*"],
              allow_credentials=True,
              allow_methods=["*"],
              allow_headers=["*"],
          )

          # Security
          security = HTTPBearer(auto_error=False)
          API_KEY = os.getenv("API_KEY", "enhancedpii123")

          # Global variables
          analyzer_engine = None
          anonymizer_engine = None
          start_time = datetime.now()

          # Request/Response Models
          class PIIRequest(BaseModel):
              text: str = Field(..., min_length=1, max_length=10000, description="Text to analyze for PII")

          class PIIResponse(BaseModel):
              has_pii: bool = Field(..., description="Whether PII was detected")
              pii_count: int = Field(..., description="Number of PII entities found")
              pii_entities: List[Dict[str, Any]] = Field(default_factory=list, description="List of PII entities")
              anonymized_text: Optional[str] = Field(None, description="Text with PII redacted")
              risk_level: str = Field(..., description="Risk assessment level")
              confidence_score: float = Field(..., description="Overall confidence score")
              processing_time_ms: float = Field(..., description="Processing time in milliseconds")

          class HealthResponse(BaseModel):
              status: str
              timestamp: str
              version: str
              service_name: str
              engine: str
              uptime_seconds: float

          def initialize_presidio():
              """Initialize Presidio analyzer with enhanced recognizers."""
              global analyzer_engine, anonymizer_engine

              try:
                  print("Initializing Presidio analyzer...")

                  # Create analyzer engine
                  analyzer_engine = AnalyzerEngine()

                  # Create anonymizer engine
                  anonymizer_engine = AnonymizerEngine()

                  # Get the registry
                  registry = analyzer_engine.registry

                  # Add enhanced recognizers for better PII detection

                  # Enhanced Email recognizer
                  email_recognizer = PatternRecognizer(
                      supported_entity="EMAIL_ADDRESS",
                      name="enhanced_email",
                      patterns=[Pattern("email", r"\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}\\b", 0.95)],
                      context=["email", "mail", "contact", "address"]
                  )
                  registry.add_recognizer(email_recognizer)

                  # Enhanced Phone recognizer
                  phone_recognizer = PatternRecognizer(
                      supported_entity="PHONE_NUMBER",
                      name="enhanced_phone",
                      patterns=[
                          Pattern("phone_us", r"\\b\\(\\d{3}\\)\\s*\\d{3}[-\\s]?\\d{4}\\b", 0.95),
                          Pattern("phone_standard", r"\\b\\d{3}[-\\s]?\\d{3}[-\\s]?\\d{4}\\b", 0.9),
                          Pattern("phone_international", r"\\b\\+?1?[-\\s]?\\(?\\d{3}\\)?[-\\s]?\\d{3}[-\\s]?\\d{4}\\b", 0.85)
                      ],
                      context=["phone", "mobile", "cell", "call", "contact", "tel"]
                  )
                  registry.add_recognizer(phone_recognizer)

                  # Enhanced Credit Card recognizer
                  credit_card_recognizer = PatternRecognizer(
                      supported_entity="CREDIT_CARD",
                      name="enhanced_credit_card",
                      patterns=[
                          Pattern("visa", r"\\b4\\d{3}[-\\s]?\\d{4}[-\\s]?\\d{4}[-\\s]?\\d{4}\\b", 0.95),
                          Pattern("mastercard", r"\\b5[1-5]\\d{2}[-\\s]?\\d{4}[-\\s]?\\d{4}[-\\s]?\\d{4}\\b", 0.95),
                          Pattern("amex", r"\\b3[47]\\d{2}[-\\s]?\\d{6}[-\\s]?\\d{5}\\b", 0.9)
                      ],
                      context=["credit", "card", "payment", "visa", "mastercard", "amex"]
                  )
                  registry.add_recognizer(credit_card_recognizer)

                  # Enhanced SSN recognizer
                  ssn_recognizer = PatternRecognizer(
                      supported_entity="US_SSN",
                      name="enhanced_ssn",
                      patterns=[
                          Pattern("ssn_hyphenated", r"\\b\\d{3}-\\d{2}-\\d{4}\\b", 0.98),
                          Pattern("ssn_spaced", r"\\b\\d{3}\\s\\d{2}\\s\\d{4}\\b", 0.9)
                      ],
                      context=["ssn", "social security", "tax id", "identification"]
                  )
                  registry.add_recognizer(ssn_recognizer)

                  # Enhanced Bank Account recognizer
                  bank_account_recognizer = PatternRecognizer(
                      supported_entity="BANK_ACCOUNT",
                      name="enhanced_bank_account",
                      patterns=[
                          Pattern("account_number", r"\\baccount\\s*#?\\s*\\d{8,17}\\b", 0.9),
                          Pattern("routing_number", r"\\brouting\\s*#?\\s*\\d{9}\\b", 0.95)
                      ],
                      context=["account", "bank", "routing", "aba", "transfer", "deposit"]
                  )
                  registry.add_recognizer(bank_account_recognizer)

                  # Enhanced IP Address recognizer
                  ip_recognizer = PatternRecognizer(
                      supported_entity="IP_ADDRESS",
                      name="enhanced_ip",
                      patterns=[
                          Pattern("ipv4", r"\\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\b", 0.95)
                      ],
                      context=["ip", "address", "network", "server"]
                  )
                  registry.add_recognizer(ip_recognizer)

                  print("Presidio analyzer initialized successfully with enhanced recognizers")
                  return True

              except Exception as e:
                  print(f"Error initializing Presidio: {e}")
                  traceback.print_exc()
                  return False

          def verify_api_key(credentials: HTTPAuthorizationCredentials = Security(security)):
              """Verify API key."""
              if credentials and credentials.credentials == API_KEY:
                  return credentials.credentials
              else:
                  raise HTTPException(
                      status_code=status.HTTP_401_UNAUTHORIZED,
                      detail="Invalid API key"
                  )

          def calculate_risk_level(entities, text_length):
              """Calculate risk level based on PII entities found."""
              if not entities:
                  return "LOW"

              high_risk_entities = ["CREDIT_CARD", "US_SSN", "BANK_ACCOUNT", "IBAN_CODE"]
              medium_risk_entities = ["PHONE_NUMBER", "EMAIL_ADDRESS", "IP_ADDRESS"]

              high_risk_count = sum(1 for e in entities if e.entity_type in high_risk_entities)
              medium_risk_count = sum(1 for e in entities if e.entity_type in medium_risk_entities)

              if high_risk_count >= 2:
                  return "CRITICAL"
              elif high_risk_count >= 1 or medium_risk_count >= 3:
                  return "HIGH"
              elif medium_risk_count >= 1 or len(entities) >= 5:
                  return "MEDIUM"
              else:
                  return "LOW"

          @app.on_event("startup")
          async def startup_event():
              """Initialize Presidio on startup."""
              success = initialize_presidio()
              if not success:
                  raise Exception("Failed to initialize Presidio PII Service")

          @app.get("/")
          async def root():
              """Root endpoint."""
              return {
                  "message": "Presidio PII Detection Service - ML POWERED",
                  "version": "1.0.0",
                  "status": "running",
                  "engine": "Microsoft Presidio",
                  "features": [
                      "25+ PII Entity Types",
                      "Context-Aware Detection",
                      "High-Precision ML Models",
                      "No False Positives",
                      "Real-time Processing"
                  ],
                  "docs_url": "/docs"
              }

          @app.get("/health")
          async def health_check():
              """Health check endpoint."""
              uptime = (datetime.now() - start_time).total_seconds()
              return HealthResponse(
                  status="healthy",
                  timestamp=datetime.now().isoformat(),
                  version="1.0.0",
                  service_name="presidio-pii-service",
                  engine="Microsoft Presidio + Spacy",
                  uptime_seconds=uptime
              )

          @app.post("/pii/detect")
          async def detect_pii(
              request: PIIRequest,
              api_key: str = Security(verify_api_key)
          ):
              """Detect PII in text using Presidio ML engine."""
              start_time = datetime.now()

              try:
                  if not analyzer_engine:
                      raise HTTPException(
                          status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                          detail="PII analyzer service not available"
                      )

                  # Analyze text with Presidio
                  results = analyzer_engine.analyze(
                      text=request.text,
                      language="en",
                      return_decision_process=True
                  )

                  # Convert results to response format
                  pii_entities = []
                  for result in results:
                      entity = {
                          "type": result.entity_type,
                          "value": request.text[result.start:result.end],
                          "confidence": result.score,
                          "start": result.start,
                          "end": result.end,
                          "detection_method": "presidio_ml"
                      }
                      pii_entities.append(entity)

                  # Generate anonymized text
                  anonymized_text = request.text
                  for result in results:
                      anonymized_text = anonymized_text[:result.start] + f"[{result.entity_type}]" + anonymized_text[result.end:]

                  # Calculate metrics
                  has_pii = len(pii_entities) > 0
                  confidence_score = sum(e["confidence"] for e in pii_entities) / len(pii_entities) if pii_entities else 0.0
                  risk_level = calculate_risk_level(results, len(request.text))
                  processing_time = (datetime.now() - start_time).total_seconds() * 1000

                  return PIIResponse(
                      has_pii=has_pii,
                      pii_count=len(pii_entities),
                      pii_entities=pii_entities,
                      anonymized_text=anonymized_text if anonymized_text != request.text else None,
                      risk_level=risk_level,
                      confidence_score=round(confidence_score, 3),
                      processing_time_ms=processing_time
                  )

              except HTTPException:
                  raise
              except Exception as e:
                  processing_time = (datetime.now() - start_time).total_seconds() * 1000
                  print(f"Error processing PII detection: {e}")
                  traceback.print_exc()

                  raise HTTPException(
                      status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                      detail=f"Error processing PII detection: {str(e)}"
                  )

          if __name__ == "__main__":
              print("🚀 Starting Presidio PII Service (ML-Powered)...")
              uvicorn.run(
                  "app:app",
                  host="0.0.0.0",
                  port=8000,
                  reload=False,
                  workers=1
              )
          PYEOF

          cd /app
          python presidio_pii_service.py
        ports:
        - containerPort: 8000
        env:
        - name: API_KEY
          value: "enhancedpii123"
        resources:
          requests:
            cpu: "300m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 45
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: pii-service-presidio
  namespace: z-grid
spec:
  selector:
    app: pii-service-presidio
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer