apiVersion: v1
kind: Service
metadata:
  name: pii-service
  namespace: z-grid
  labels:
    app: pii-service
    component: pii-detection
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: pii-service