apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-service-fixed
  namespace: z-grid
  labels:
    app: secrets-service-fixed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secrets-service-fixed
  template:
    metadata:
      labels:
        app: secrets-service-fixed
    spec:
      containers:
      - name: secrets-service-fixed
        image: python:3.11-slim
        command:
        - /bin/bash
        - -c
        - |
          set -e
          echo "Installing Flask..."
          pip install flask requests
          echo "Starting Secrets Service..."
          cat > /tmp/secrets_app.py << 'PYEOF'
          from flask import Flask, request, jsonify
          from datetime import datetime
          import re
          import os

          app = Flask(__name__)
          SECRETS_API_KEYS = ['secrets123', 'supersecret123', 'biasyavar', 'enhancedsecrets123']

          SECRET_PATTERNS = {
              'api_key': r'(?i)api[_\\-\\s]?key[\\s:=]+([a-zA-Z0-9_\\-]{16,})',
              'aws_access_key': r'AKIA[0-9A-Z]{16}',
              'password': r'(?i)password[\\s:=]+([^\\s]{6,})',
              'jwt': r'eyJ[a-zA-Z0-9._-]*\\.eyJ[a-zA-Z0-9._-]*\\.[a-zA-Z0-9._-]*'
          }

          def validate_api_key():
              api_key = request.headers.get('X-API-Key')
              return api_key in SECRETS_API_KEYS

          def detect_secrets(text):
              findings = []
              for secret_type, pattern in SECRET_PATTERNS.items():
                  matches = re.finditer(pattern, text)
                  for match in matches:
                      secret_value = match.group(1) if match.groups() else match.group(0)
                      masked = secret_value[:6] + '*' * (len(secret_value) - 12) + secret_value[-6:] if len(secret_value) > 12 else '*' * len(secret_value)
                      findings.append({
                          'type': secret_type,
                          'confidence': 0.9,
                          'matched_text': masked,
                          'position': match.start()
                      })
              return findings

          @app.route('/health', methods=['GET'])
          def health():
              return jsonify({
                  'ok': True,
                  'service': 'Secrets Detection Service',
                  'status': 'running',
                  'timestamp': datetime.now().isoformat()
              })

          @app.route('/secrets/scan', methods=['POST'])
          def scan_secrets():
              if not validate_api_key():
                  return jsonify({'error': 'Invalid API key'}), 401

              data = request.get_json()
              if not data or 'text' not in data:
                  return jsonify({'error': 'Text is required'}), 400

              text = data['text']
              findings = detect_secrets(text)
              risk_score = min(len(findings) * 0.3, 1.0)

              return jsonify({
                  'text_length': len(text),
                  'secrets_found': len(findings),
                  'risk_score': round(risk_score, 2),
                  'high_risk': risk_score > 0.7,
                  'findings': findings,
                  'scan_time': datetime.now().isoformat()
              })

          if __name__ == '__main__':
              print("🚀 Secrets Service Starting on port 8005...")
              app.run(host='0.0.0.0', port=8005, debug=False)
          PYEOF
          python3 /tmp/secrets_app.py
        ports:
        - containerPort: 8005
        env:
        - name: SECRETS_API_KEYS
          value: "secrets123,supersecret123,biasyavar,enhancedsecrets123"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: secrets-service-fixed
  namespace: z-grid
spec:
  selector:
    app: secrets-service-fixed
  ports:
  - port: 8005
    targetPort: 8005
  type: LoadBalancer