{{- /*
Secret template for jailbreak detection service
*/ -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jailbreak-distilbert.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jailbreak-distilbert.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
  annotations:
    description: "API keys and secrets for jailbreak detection service"

type: Opaque
data:
  # API Keys (base64 encoded)
  API_KEYS: {{ .Values.api.keys | b64enc }}

  # Authentication header
  AUTH_HEADER_NAME: {{ "x-api-key" | b64enc }}

  # Monitoring tokens (optional)
  PROMETHEUS_TOKEN: {{ "" | b64enc }}
  LOG_TOKEN: {{ "" | b64enc }}